services:
  thegame:
    build:
      context: .
      target: dev
    volumes:
      - .:/workspace:cached
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/workspace/target
    environment:
      - CARGO_TERM_COLOR=always
      - RUST_BACKTRACE=1
      - DISPLAY=${DISPLAY:-}
    command: ["cargo", "run"]
volumes:
  cargo-registry:
  cargo-git:
  target-cache:
