[defaults]
min = 0.0
max = 100.0
start = 60.0

[decay]
per_second = 0.25

[gains]
task = 8.0
social = 6.0
leisure = 5.0

[dependency]
satisfaction_bonus = 4.0
deficit_penalty = 7.5

[mood_thresholds]
energised = 80.0
content = 55.0
tired = 30.0

[alcohol]
boost = 12.0
intoxication_seconds = 90.0
hangover_penalty = 15.0
hangover_decay_multiplier = 1.6
hangover_duration_seconds = 180.0
quality_penalty = 0.2
trigger_keywords = ["tavern", "ale", "mead", "wine"]

[leisure]
keywords = ["supper", "stories", "lute", "rest", "tavern"]
