# Simulation time configuration
[clock]
# Length of an in-game day in real-world minutes (before time scaling)
day_length_minutes = 10.0
# Fraction of the day marking sunrise (0-1)
sunrise_fraction = 0.22
# Fraction of the day marking sunset (0-1)
sunset_fraction = 0.78
# Tilt of the sun in radians (positive tilts sun towards evening)
sun_declination_radians = 0.4

[lighting]
# Maximum directional light intensity at noon
noon_lux = 50000.0
# Minimum directional light intensity at night
night_lux = 5.0
# Ambient light levels for day and night
ambient_day = [0.35, 0.35, 0.4]
ambient_night = [0.05, 0.05, 0.1]
